name: GitHub Actions Demo
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Scavenge
        uses: anaynayak/python-vulture-action@v1.0
        id: vulture
        with:
          vulture-args: example --min-confidence 90
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          version: "~= 22.0"
